// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(safeparts_swiftFFI)
import safeparts_swiftFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_safeparts_swift_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_safeparts_swift_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureSafepartsSwiftInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt8: FfiConverterPrimitive {
    typealias FfiType = UInt8
    typealias SwiftType = UInt8

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt8 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: UInt8, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}


public struct EncodedShare {
    public var text: String
    public var index: UInt8
    public var shareCount: UInt8
    public var setId: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(text: String, index: UInt8, shareCount: UInt8, setId: String) {
        self.text = text
        self.index = index
        self.shareCount = shareCount
        self.setId = setId
    }
}

#if compiler(>=6)
extension EncodedShare: Sendable {}
#endif


extension EncodedShare: Equatable, Hashable {
    public static func ==(lhs: EncodedShare, rhs: EncodedShare) -> Bool {
        if lhs.text != rhs.text {
            return false
        }
        if lhs.index != rhs.index {
            return false
        }
        if lhs.shareCount != rhs.shareCount {
            return false
        }
        if lhs.setId != rhs.setId {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(text)
        hasher.combine(index)
        hasher.combine(shareCount)
        hasher.combine(setId)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeEncodedShare: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> EncodedShare {
        return
            try EncodedShare(
                text: FfiConverterString.read(from: &buf), 
                index: FfiConverterUInt8.read(from: &buf), 
                shareCount: FfiConverterUInt8.read(from: &buf), 
                setId: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: EncodedShare, into buf: inout [UInt8]) {
        FfiConverterString.write(value.text, into: &buf)
        FfiConverterUInt8.write(value.index, into: &buf)
        FfiConverterUInt8.write(value.shareCount, into: &buf)
        FfiConverterString.write(value.setId, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEncodedShare_lift(_ buf: RustBuffer) throws -> EncodedShare {
    return try FfiConverterTypeEncodedShare.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEncodedShare_lower(_ value: EncodedShare) -> RustBuffer {
    return FfiConverterTypeEncodedShare.lower(value)
}


public struct Inspection {
    public var detectedEncoding: ShareEncoding
    public var threshold: UInt8
    public var shareCount: UInt8
    public var providedCount: UInt32
    public var encrypted: Bool
    public var indexes: Data
    public var consistent: Bool
    public var ready: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(detectedEncoding: ShareEncoding, threshold: UInt8, shareCount: UInt8, providedCount: UInt32, encrypted: Bool, indexes: Data, consistent: Bool, ready: Bool) {
        self.detectedEncoding = detectedEncoding
        self.threshold = threshold
        self.shareCount = shareCount
        self.providedCount = providedCount
        self.encrypted = encrypted
        self.indexes = indexes
        self.consistent = consistent
        self.ready = ready
    }
}

#if compiler(>=6)
extension Inspection: Sendable {}
#endif


extension Inspection: Equatable, Hashable {
    public static func ==(lhs: Inspection, rhs: Inspection) -> Bool {
        if lhs.detectedEncoding != rhs.detectedEncoding {
            return false
        }
        if lhs.threshold != rhs.threshold {
            return false
        }
        if lhs.shareCount != rhs.shareCount {
            return false
        }
        if lhs.providedCount != rhs.providedCount {
            return false
        }
        if lhs.encrypted != rhs.encrypted {
            return false
        }
        if lhs.indexes != rhs.indexes {
            return false
        }
        if lhs.consistent != rhs.consistent {
            return false
        }
        if lhs.ready != rhs.ready {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(detectedEncoding)
        hasher.combine(threshold)
        hasher.combine(shareCount)
        hasher.combine(providedCount)
        hasher.combine(encrypted)
        hasher.combine(indexes)
        hasher.combine(consistent)
        hasher.combine(ready)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeInspection: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Inspection {
        return
            try Inspection(
                detectedEncoding: FfiConverterTypeShareEncoding.read(from: &buf), 
                threshold: FfiConverterUInt8.read(from: &buf), 
                shareCount: FfiConverterUInt8.read(from: &buf), 
                providedCount: FfiConverterUInt32.read(from: &buf), 
                encrypted: FfiConverterBool.read(from: &buf), 
                indexes: FfiConverterData.read(from: &buf), 
                consistent: FfiConverterBool.read(from: &buf), 
                ready: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: Inspection, into buf: inout [UInt8]) {
        FfiConverterTypeShareEncoding.write(value.detectedEncoding, into: &buf)
        FfiConverterUInt8.write(value.threshold, into: &buf)
        FfiConverterUInt8.write(value.shareCount, into: &buf)
        FfiConverterUInt32.write(value.providedCount, into: &buf)
        FfiConverterBool.write(value.encrypted, into: &buf)
        FfiConverterData.write(value.indexes, into: &buf)
        FfiConverterBool.write(value.consistent, into: &buf)
        FfiConverterBool.write(value.ready, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeInspection_lift(_ buf: RustBuffer) throws -> Inspection {
    return try FfiConverterTypeInspection.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeInspection_lower(_ value: Inspection) -> RustBuffer {
    return FfiConverterTypeInspection.lower(value)
}


public struct Recovery {
    public var bytes: Data
    public var detectedEncoding: ShareEncoding
    public var threshold: UInt8
    public var shareCount: UInt8
    public var encrypted: Bool
    public var indexes: Data
    public var setId: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(bytes: Data, detectedEncoding: ShareEncoding, threshold: UInt8, shareCount: UInt8, encrypted: Bool, indexes: Data, setId: String) {
        self.bytes = bytes
        self.detectedEncoding = detectedEncoding
        self.threshold = threshold
        self.shareCount = shareCount
        self.encrypted = encrypted
        self.indexes = indexes
        self.setId = setId
    }
}

#if compiler(>=6)
extension Recovery: Sendable {}
#endif


extension Recovery: Equatable, Hashable {
    public static func ==(lhs: Recovery, rhs: Recovery) -> Bool {
        if lhs.bytes != rhs.bytes {
            return false
        }
        if lhs.detectedEncoding != rhs.detectedEncoding {
            return false
        }
        if lhs.threshold != rhs.threshold {
            return false
        }
        if lhs.shareCount != rhs.shareCount {
            return false
        }
        if lhs.encrypted != rhs.encrypted {
            return false
        }
        if lhs.indexes != rhs.indexes {
            return false
        }
        if lhs.setId != rhs.setId {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(bytes)
        hasher.combine(detectedEncoding)
        hasher.combine(threshold)
        hasher.combine(shareCount)
        hasher.combine(encrypted)
        hasher.combine(indexes)
        hasher.combine(setId)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeRecovery: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Recovery {
        return
            try Recovery(
                bytes: FfiConverterData.read(from: &buf), 
                detectedEncoding: FfiConverterTypeShareEncoding.read(from: &buf), 
                threshold: FfiConverterUInt8.read(from: &buf), 
                shareCount: FfiConverterUInt8.read(from: &buf), 
                encrypted: FfiConverterBool.read(from: &buf), 
                indexes: FfiConverterData.read(from: &buf), 
                setId: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: Recovery, into buf: inout [UInt8]) {
        FfiConverterData.write(value.bytes, into: &buf)
        FfiConverterTypeShareEncoding.write(value.detectedEncoding, into: &buf)
        FfiConverterUInt8.write(value.threshold, into: &buf)
        FfiConverterUInt8.write(value.shareCount, into: &buf)
        FfiConverterBool.write(value.encrypted, into: &buf)
        FfiConverterData.write(value.indexes, into: &buf)
        FfiConverterString.write(value.setId, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRecovery_lift(_ buf: RustBuffer) throws -> Recovery {
    return try FfiConverterTypeRecovery.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRecovery_lower(_ value: Recovery) -> RustBuffer {
    return FfiConverterTypeRecovery.lower(value)
}


public enum BridgeError: Swift.Error {

    
    
    case InvalidParameters
    case InvalidEncoding
    case EmptyInput
    case MalformedShares
    case InsufficientShares
    case DuplicateShares
    case MixedShares
    case PassphraseRequired
    case IncorrectPassphrase
    case IntegrityFailure
    case Internal
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeBridgeError: FfiConverterRustBuffer {
    typealias SwiftType = BridgeError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> BridgeError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .InvalidParameters
        case 2: return .InvalidEncoding
        case 3: return .EmptyInput
        case 4: return .MalformedShares
        case 5: return .InsufficientShares
        case 6: return .DuplicateShares
        case 7: return .MixedShares
        case 8: return .PassphraseRequired
        case 9: return .IncorrectPassphrase
        case 10: return .IntegrityFailure
        case 11: return .Internal

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: BridgeError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case .InvalidParameters:
            writeInt(&buf, Int32(1))
        
        
        case .InvalidEncoding:
            writeInt(&buf, Int32(2))
        
        
        case .EmptyInput:
            writeInt(&buf, Int32(3))
        
        
        case .MalformedShares:
            writeInt(&buf, Int32(4))
        
        
        case .InsufficientShares:
            writeInt(&buf, Int32(5))
        
        
        case .DuplicateShares:
            writeInt(&buf, Int32(6))
        
        
        case .MixedShares:
            writeInt(&buf, Int32(7))
        
        
        case .PassphraseRequired:
            writeInt(&buf, Int32(8))
        
        
        case .IncorrectPassphrase:
            writeInt(&buf, Int32(9))
        
        
        case .IntegrityFailure:
            writeInt(&buf, Int32(10))
        
        
        case .Internal:
            writeInt(&buf, Int32(11))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBridgeError_lift(_ buf: RustBuffer) throws -> BridgeError {
    return try FfiConverterTypeBridgeError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBridgeError_lower(_ value: BridgeError) -> RustBuffer {
    return FfiConverterTypeBridgeError.lower(value)
}


extension BridgeError: Equatable, Hashable {}




extension BridgeError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}




// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum ShareEncoding {
    
    case auto
    case base64url
    case base58check
    case mnemoWords
    case mnemoBip39
}


#if compiler(>=6)
extension ShareEncoding: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeShareEncoding: FfiConverterRustBuffer {
    typealias SwiftType = ShareEncoding

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ShareEncoding {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .auto
        
        case 2: return .base64url
        
        case 3: return .base58check
        
        case 4: return .mnemoWords
        
        case 5: return .mnemoBip39
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: ShareEncoding, into buf: inout [UInt8]) {
        switch value {
        
        
        case .auto:
            writeInt(&buf, Int32(1))
        
        
        case .base64url:
            writeInt(&buf, Int32(2))
        
        
        case .base58check:
            writeInt(&buf, Int32(3))
        
        
        case .mnemoWords:
            writeInt(&buf, Int32(4))
        
        
        case .mnemoBip39:
            writeInt(&buf, Int32(5))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeShareEncoding_lift(_ buf: RustBuffer) throws -> ShareEncoding {
    return try FfiConverterTypeShareEncoding.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeShareEncoding_lower(_ value: ShareEncoding) -> RustBuffer {
    return FfiConverterTypeShareEncoding.lower(value)
}


extension ShareEncoding: Equatable, Hashable {}






#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeEncodedShare: FfiConverterRustBuffer {
    typealias SwiftType = [EncodedShare]

    public static func write(_ value: [EncodedShare], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeEncodedShare.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [EncodedShare] {
        let len: Int32 = try readInt(&buf)
        var seq = [EncodedShare]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeEncodedShare.read(from: &buf))
        }
        return seq
    }
}
public func combineShareInput(input: String, selected: ShareEncoding, passphrase: String?)throws  -> Recovery  {
    return try  FfiConverterTypeRecovery_lift(try rustCallWithError(FfiConverterTypeBridgeError_lift) {
    uniffi_safeparts_swift_fn_func_combine_share_input(
        FfiConverterString.lower(input),
        FfiConverterTypeShareEncoding_lower(selected),
        FfiConverterOptionString.lower(passphrase),$0
    )
})
}
public func inspectShareInput(input: String, selected: ShareEncoding)throws  -> Inspection  {
    return try  FfiConverterTypeInspection_lift(try rustCallWithError(FfiConverterTypeBridgeError_lift) {
    uniffi_safeparts_swift_fn_func_inspect_share_input(
        FfiConverterString.lower(input),
        FfiConverterTypeShareEncoding_lower(selected),$0
    )
})
}
public func splitSecret(secret: Data, threshold: UInt8, shareCount: UInt8, selected: ShareEncoding, passphrase: String?)throws  -> [EncodedShare]  {
    return try  FfiConverterSequenceTypeEncodedShare.lift(try rustCallWithError(FfiConverterTypeBridgeError_lift) {
    uniffi_safeparts_swift_fn_func_split_secret(
        FfiConverterData.lower(secret),
        FfiConverterUInt8.lower(threshold),
        FfiConverterUInt8.lower(shareCount),
        FfiConverterTypeShareEncoding_lower(selected),
        FfiConverterOptionString.lower(passphrase),$0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 29
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_safeparts_swift_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_safeparts_swift_checksum_func_combine_share_input() != 5825) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_safeparts_swift_checksum_func_inspect_share_input() != 49328) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_safeparts_swift_checksum_func_split_secret() != 25138) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureSafepartsSwiftInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all