type SafepartsWasm = typeof import('./wasm_pkg/safeparts_wasm')
type RecoveredBytes = Uint8Array | ArrayBuffer | ArrayLike<number>

let cached: SafepartsWasm | null = null

export function recoveredSecretText(bytes: RecoveredBytes): string | null {
  const recovered =
    bytes instanceof Uint8Array
      ? bytes
      : bytes instanceof ArrayBuffer
        ? new Uint8Array(bytes)
        : new Uint8Array(Array.from(bytes))

  try {
    return new TextDecoder('utf-8', { fatal: true, ignoreBOM: true }).decode(recovered)
  } catch {
    return null
  }
}

export async function ensureWasm(): Promise<SafepartsWasm> {
  if (cached) return cached

  // Generated by `wasm-pack build --target web --out-dir src/wasm_pkg`
  const mod = await import('./wasm_pkg/safeparts_wasm')

  // wasm-pack exports an `init` function for the actual wasm.
  if (typeof mod.default === 'function') {
    await mod.default()
  }

  cached = mod
  return cached
}
