// @ts-nocheck
let cached: any | null = null

export async function ensureWasm(): Promise<any> {
  if (cached) return cached

  // Generated by `wasm-pack build --target web --out-dir src/wasm_pkg`
  const mod = await import('./wasm_pkg/ssss_mnemo_wasm')

  // wasm-pack exports an `init` function for the actual wasm.
  if (typeof mod.default === 'function') {
    await mod.default()
  }

  cached = mod
  return cached
}
